In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding="latin-1")
pd.DataFrame(df)

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [30]:
year_17 = df.groupby("Area")["Y2017"].sum().reset_index()
print(year_17)
max_year = year_17[year_17["Y2017"] == year_17["Y2017"].max()]
print(max_year)
min_year = year_17[year_17["Y2017"] == year_17["Y2017"].min()]
print(min_year)

                           Area       Y2017
0                       Algeria   325644.27
1                        Angola   229159.57
2                         Benin   124771.22
3                      Botswana    22101.30
4                  Burkina Faso   101855.07
5                    Cabo Verde    14650.74
6                      Cameroon   232030.43
7      Central African Republic    29937.00
8                          Chad    71594.68
9                       Comoros       59.84
10                        Congo    41181.68
11                CÃ´te d'Ivoire   224599.01
12                     Djibouti    22729.91
13                        Egypt   866379.92
14                     Eswatini    54343.33
15                     Ethiopia   448683.76
16                 Ethiopia PDR        0.00
17                        Gabon    27979.64
18                       Gambia    23154.18
19                        Ghana   337599.06
20                       Guinea    98138.87
21                Guinea-Bissau    19102.77
22                        Kenya   264660.66
23                      Lesotho    21267.96
24                      Liberia    29342.20
25                   Madagascar   131197.73
26                       Malawi   181098.71
27                         Mali   149928.33
28                   Mauritania   156665.46
29                    Mauritius    51114.83
30                      Morocco   388495.36
31                   Mozambique   161407.98
32                      Namibia    29874.89
33                        Niger   126707.58
34                      Nigeria  1483268.23
35                       Rwanda    73663.69
36        Sao Tome and Principe    12662.63
37                      Senegal    95681.15
38                   Seychelles      442.34
39                 Sierra Leone    55311.33
40                 South Africa   517590.54
41                        Sudan   239931.92
42               Sudan (former)        0.00
43                         Togo    49841.88
44                      Tunisia   124167.20
45                       Uganda   213950.38
46  United Republic of Tanzania   322616.85
47                       Zambia   103223.77
48                     Zimbabwe    75919.34
       Area       Y2017
34  Nigeria  1483268.23
              Area  Y2017
16    Ethiopia PDR    0.0
42  Sudan (former)    0.0

In [31]:
df["Y2017"].describe()

count     59437.000000
mean        140.917765
std        1671.862359
min       -1582.000000
25%           0.000000
50%           0.100000
75%           9.000000
max      190873.000000
Name: Y2017, dtype: float64

In [32]:
missing_sum = df["Y2014"].isnull().sum()
total_count = df["Y2014"].count()
print (f"The total number of missing values in Y2014 is {missing_sum} and the percentage of missing values is {missing_sum/total_count*100}%")

The total number of missing values in Y2014 is 1589 and the percentage of missing values is 2.6771573946153584%

In [35]:
condition = (df["Area"] == "Madagascar") & (df["Element"] == "Protein supply quantity (g/capita/day)")
supply = df.loc[condition, "Y2015"].sum()
#print((condition==True).sum())
print(f"The total Protein supply quantity in Madagascar in 2015 is: {supply}")

The total Protein supply quantity in Madagascar in 2015 is: 173.04999999999998

In [41]:
sorted_year_17 = year_17.sort_values(by="Y2017", ascending=True)
seventh_lowest = sorted_year_17.iloc[6,0]
print(f"{seventh_lowest} had the seventh lowest sum in 2017")

Guinea-Bissau had the seventh lowest sum in 2017

In [44]:
element_group = df.groupby("Element")["Y2017"].sum().reset_index()
processing = element_group.iloc[10,1]
print(f"The total number of the sum of Processing in 2017 is: {processing}")

The total number of the sum of Processing in 2017 is: 292836.0

In [59]:
all_group = df.groupby("Element")
y_14= all_group["Y2014"].sum().reset_index()
y_15= all_group["Y2015"].sum().reset_index()
y_16= all_group["Y2016"].sum().reset_index()
y_17= all_group["Y2017"].sum().reset_index()
y_18= all_group["Y2018"].sum().reset_index()
stock = [y_14.iloc[15,], y_15.iloc[15,], y_16.iloc[15,], y_17.iloc[15,], y_18.iloc[15,]]
print(stock)
print(f"Year 2014 had the highest total stock variation with a value of {y_14.iat[15,1]}")

[Element    Stock Variation
Y2014             58749.83
Name: 15, dtype: object, Element    Stock Variation
Y2015             34910.99
Name: 15, dtype: object, Element    Stock Variation
Y2016             33140.12
Name: 15, dtype: object, Element    Stock Variation
Y2017             54316.91
Name: 15, dtype: object, Element    Stock Variation
Y2018             20577.91
Name: 15, dtype: object]
Year 2014 had the highest total stock variation with a value of 58749.83

In [62]:
all_group.describe()

                                       Area Code                              \
                                           count        mean        std  min
Element
Domestic supply quantity                  5295.0  133.898584  72.429582  4.0
Export Quantity                           4403.0  136.250284  72.474261  4.0
Fat supply quantity (g/capita/day)        5023.0  134.391798  72.408886  4.0
Feed                                      1319.0  133.640637  71.452934  4.0
Food                                      4941.0  134.243068  72.466059  4.0
Food supply (kcal/capita/day)             5014.0  134.434982  72.358700  4.0
Food supply quantity (kg/capita/yr)       4905.0  134.239755  72.455564  4.0
Import Quantity                           5139.0  133.912045  72.365119  4.0
Losses                                    2009.0  136.561971  72.785591  4.0
Other uses (non-food)                     1732.0  136.001155  73.106619  4.0
Processing                                2010.0  135.293532  74.949822  4.0
Production                                3881.0  135.725586  72.972281  4.0
Protein supply quantity (g/capita/day)    5023.0  134.391798  72.408886  4.0
Residuals                                 4655.0  133.892803  72.429026  4.0
Seed                                       762.0  135.875328  73.266647  4.0
Stock Variation                           4232.0  135.058129  72.874997  4.0
Total Population - Both sexes               45.0  133.777778  73.112581  4.0
Tourist consumption                        555.0   90.645045  59.925421  7.0

                                                                  Item Code  \
                                         25%    50%    75%    max     count
Element
Domestic supply quantity                74.0  136.0  195.0  276.0    5295.0
Export Quantity                         75.0  137.0  197.0  276.0    4403.0
Fat supply quantity (g/capita/day)      74.0  136.0  195.0  276.0    5023.0
Feed                                    74.0  133.0  197.0  276.0    1319.0
Food                                    74.0  136.0  195.0  276.0    4941.0
Food supply (kcal/capita/day)           74.0  136.0  195.0  276.0    5014.0
Food supply quantity (kg/capita/yr)     74.0  136.0  195.0  276.0    4905.0
Import Quantity                         74.0  136.0  195.0  276.0    5139.0
Losses                                  74.0  137.0  197.0  276.0    2009.0
Other uses (non-food)                   74.0  137.0  202.0  276.0    1732.0
Processing                              59.0  143.0  195.0  276.0    2010.0
Production                              74.0  137.0  197.0  276.0    3881.0
Protein supply quantity (g/capita/day)  74.0  136.0  195.0  276.0    5023.0
Residuals                               74.0  136.0  195.0  276.0    4655.0
Seed                                    74.0  137.0  202.0  276.0     762.0
Stock Variation                         74.0  137.0  197.0  276.0    4232.0
Total Population - Both sexes           74.0  136.0  195.0  276.0      45.0
Tourist consumption                     35.0   59.0  137.0  193.0     555.0

                                                     ...       Y2017  \
                                               mean  ...         75%
Element                                              ...
Domestic supply quantity                2681.292729  ...     81.0000
Export Quantity                         2689.201226  ...      3.1350
Fat supply quantity (g/capita/day)      2694.604818  ...      0.5075
Feed                                    2682.719484  ...     26.0000
Food                                    2688.734062  ...     63.0000
Food supply (kcal/capita/day)           2694.666933  ...     26.0000
Food supply quantity (kg/capita/yr)     2688.155148  ...      5.7625
Import Quantity                         2684.562366  ...      8.0000
Losses                                  2700.250373  ...     31.0000
Other uses (non-food)                   2730.801963  ...      2.0000
Processing                              2661.898507  ...      5.0000
Production                              2692.618655  ...    152.0000
Protein supply quantity (g/capita/day)  2694.604818  ...      0.6400
Residuals                               2668.332760  ...      0.0000
Seed                                    2671.828084  ...     23.0000
Stock Variation                         2677.109405  ...      1.0000
Total Population - Both sexes           2501.000000  ...  29121.0000
Tourist consumption                     2678.428829  ...      0.0000

                                                    Y2018                \
                                              max   count          mean
Element
Domestic supply quantity                112625.00  5256.0    411.185712
Export Quantity                          34641.00  3646.0     49.806583
Fat supply quantity (g/capita/day)          97.13  4987.0      2.057086
Feed                                     29580.00  1225.0    190.603820
Food                                     51220.00  4913.0    265.385972
Food supply (kcal/capita/day)             3457.00  4969.0     91.620246
Food supply quantity (kg/capita/yr)        433.38  4877.0     10.058817
Import Quantity                          18627.00  4945.0     58.240059
Losses                                   10342.00  2008.0     81.624502
Other uses (non-food)                    17219.00  1655.0     55.166749
Processing                               22174.00  2003.0    153.983525
Production                              117702.00  3846.0    539.540533
Protein supply quantity (g/capita/day)     100.10  4986.0      2.373357
Residuals                                17476.00  4616.0      7.552860
Seed                                      1453.00   758.0     33.328681
Stock Variation                           5089.00  4217.0      4.879751
Total Population - Both sexes           190873.00    45.0  25346.777778
Tourist consumption                          6.00   555.0      0.162162

                                                                         \
                                                 std     min        25%
Element
Domestic supply quantity                 2544.664930  -184.0     0.0000
Export Quantity                           842.633449     0.0     0.0000
Fat supply quantity (g/capita/day)          7.799864     0.0     0.0000
Feed                                     1382.718629     0.0     0.0000
Food                                     1407.952979     0.0     0.0000
Food supply (kcal/capita/day)             357.469150     0.0     0.0000
Food supply quantity (kg/capita/yr)        29.555214     0.0     0.0100
Import Quantity                           467.670555     0.0     0.0000
Losses                                    402.263215     0.0     0.0000
Other uses (non-food)                     497.694277     0.0     0.0000
Processing                               1022.278276     0.0     0.0000
Production                               3019.990719     0.0     0.1625
Protein supply quantity (g/capita/day)      8.933189     0.0     0.0000
Residuals                                 363.873325  -598.0     0.0000
Seed                                      105.787366     0.0     1.0000
Stock Variation                           132.428693 -3396.0     0.0000
Total Population - Both sexes           35337.267187   211.0  4403.0000
Tourist consumption                         0.617736     0.0     0.0000


                                             50%         75%        max
Element
Domestic supply quantity                    7.00     82.0000  117038.00
Export Quantity                             0.00      3.0000   34641.00
Fat supply quantity (g/capita/day)          0.03      0.4900      94.94
Feed                                        0.20     24.0000   31567.00
Food                                        5.38     63.8800   54077.00
Food supply (kcal/capita/day)               3.00     26.0000    3450.00
Food supply quantity (kg/capita/yr)         0.60      5.6900     443.56
Import Quantity                             0.48      8.0000   18036.00
Losses                                      4.00     31.0000   10355.00
Other uses (non-food)                       0.00      2.0000   17221.00
Processing                                  0.00      5.0000   22609.00
Production                                 16.00    153.7500  118172.00
Protein supply quantity (g/capita/day)      0.03      0.6475     101.08
Residuals                                   0.00      0.0000   17323.00
Seed                                        4.00     22.7500    1474.00
Stock Variation                             0.00      0.0000    2226.00
Total Population - Both sexes           15478.00  29767.0000  195875.00
Tourist consumption                         0.00      0.0000       6.00

[18 rows x 64 columns]

In [69]:
item_total_15 = df.groupby("Item")["Y2015"].sum().reset_index()
item_total_18 = df.groupby("Item")["Y2018"].sum().reset_index()
print(f"The total sum of Wine produced in 2015 is: {item_total_15.loc[117, 'Y2015']}")
print(f"The total sum of Wine produced in 2018 is: {item_total_18.loc[117, 'Y2018']}")

The total sum of Wine produced in 2015 is: 4251.81
The total sum of Wine produced in 2018 is: 4039.32